name = "KOrderPerturbations"
uuid = "469b1a10-d817-41b3-9228-c19fbf63afb5"
authors = ["MichelJuillard <michel.juillard@mjui.fr>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
FastLapackInterface = "29a986be-02c6-4525-aec4-84b980013641"
GeneralizedSylvesterSolver = "3b00829b-373b-4a35-afa6-09f888b04ecd"
KroneckerTools = "7e59e93b-e0cb-42c7-aa95-426cb754d61e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compta]
Combinatorics = "1.0.2"
FastLapackInterface = "1"
GeneralizedSylvesterSolver = "0.1.2"
KroneckerTools = "0.1.1"